name: LOTRPlugin
version: "0.1"
api-version: "0.1"
author: Combattant54
authors:
  - Ph1lou
  - Combattant54
main: fr.combattant54.lotrplugin.Main
load: STARTUP
commands:
  lotr:
    description: player commands
  a:
    description: admin commands


